### ISSUE TITLE
[Fix][Documentation] Find the error and correct it 

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Hacktoberfest-2021#1]

**Comment by raymax0x** [comment]
On it.

**Comment by adityamangal1** [comment]
Hey, @Recognizeyourself Can you please join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 join.bauddhikgeeks.tech

**Comment by raymax0x** [comment]
Done !!

**Comment by raymax0x** [comment]
In discord server its showing this : 

![image](https://user-images.githubusercontent.com/35026190/135492291-9dea9b6a-3e1e-4a3c-a91d-7ee7e7e73eb9.png)

**Comment by harikanani** [comment]
> In discord server its showing this :
> 
> ![image](https://user-images.githubusercontent.com/35026190/135492291-9dea9b6a-3e1e-4a3c-a91d-7ee7e7e73eb9.png)

Accept invite

**Comment by rhvsingh** [comment]
I want to work on this issue

**Comment by harikanani** [comment]
Go ahead @rhvsingh 👍

**Comment by thedrivingforc** [comment]
I would like to make some fixes in the doc as it says we need 5 PRs but officially 4 PRs are needed. Can you please assign me this issue so that I can help out there? @Nitesh-thapliyal @adityamangal1

**Comment by harikanani** [comment]
> I would like to make some fixes in the doc as it says we need 5 PRs but officially 4 PRs are needed. Can you please assign me this issue so that I can help out there? @Nitesh-thapliyal @adityamangal1

Sure go ahead @thedrivingforc 👍

**Comment by thedrivingforc** [comment]
On it
