### ISSUE TITLE
Remove the visitors badge

### ISSUE THREAD

**Issue by suitupstan** [Bauddhik-Geeks/Hacktoberfest-2021#2]
Remove the visitors badge since its not accurate and can be incremented on refreshing

**Comment by suitupstan** [comment]
Can I be assigned?

**Comment by adityamangal1** [comment]
Sure @krishguptadev, can you suggest more badges then or any new feature? So I can assign you for that

**Comment by suitupstan** [comment]
I suggest a code of conduct as well

**Comment by suitupstan** [comment]
and a all contributors badge ig

**Comment by adityamangal1** [comment]
There is code of conduct already btw but you can add your suggested badge

**Comment by suitupstan** [comment]
I don't see the coc 
![image](https://user-images.githubusercontent.com/91655303/135589713-ca50e3b8-c6ca-4d53-8cfb-73dd6ca2fea1.png)

**Comment by adityamangal1** [comment]
I haven't upload the individual file but read the readme there was coc and it's  link which was already updated by a contributor  and will be merged soon. bcoz this is not a complex repo that's why 
Hope this helps

**Comment by suitupstan** [comment]
@adityamangal1 kindly review #4 and #5
